// flow-typed signature: 032300d531e93bcb03c367748aac2515
// flow-typed version: <<STUB>>/react-titles_v^1.0.2/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-titles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-titles' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-titles/src' {
  declare module.exports: any
}

declare module 'react-titles/src/Title1' {
  declare module.exports: any
}

declare module 'react-titles/src/Title10' {
  declare module.exports: any
}

declare module 'react-titles/src/Title11' {
  declare module.exports: any
}

declare module 'react-titles/src/Title2' {
  declare module.exports: any
}

declare module 'react-titles/src/Title3' {
  declare module.exports: any
}

declare module 'react-titles/src/Title4' {
  declare module.exports: any
}

declare module 'react-titles/src/Title5' {
  declare module.exports: any
}

declare module 'react-titles/src/Title6' {
  declare module.exports: any
}

declare module 'react-titles/src/Title7' {
  declare module.exports: any
}

declare module 'react-titles/src/Title8' {
  declare module.exports: any
}

declare module 'react-titles/src/Title9' {
  declare module.exports: any
}

declare module 'react-titles/Title1' {
  declare module.exports: any
}

declare module 'react-titles/Title10' {
  declare module.exports: any
}

declare module 'react-titles/Title11' {
  declare module.exports: any
}

declare module 'react-titles/Title2' {
  declare module.exports: any
}

declare module 'react-titles/Title3' {
  declare module.exports: any
}

declare module 'react-titles/Title4' {
  declare module.exports: any
}

declare module 'react-titles/Title5' {
  declare module.exports: any
}

declare module 'react-titles/Title6' {
  declare module.exports: any
}

declare module 'react-titles/Title7' {
  declare module.exports: any
}

declare module 'react-titles/Title8' {
  declare module.exports: any
}

declare module 'react-titles/Title9' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-titles/index' {
  declare module.exports: $Exports<'react-titles'>
}
declare module 'react-titles/index.js' {
  declare module.exports: $Exports<'react-titles'>
}
declare module 'react-titles/src/index' {
  declare module.exports: $Exports<'react-titles/src'>
}
declare module 'react-titles/src/index.js' {
  declare module.exports: $Exports<'react-titles/src'>
}
declare module 'react-titles/src/Title1.js' {
  declare module.exports: $Exports<'react-titles/src/Title1'>
}
declare module 'react-titles/src/Title10.js' {
  declare module.exports: $Exports<'react-titles/src/Title10'>
}
declare module 'react-titles/src/Title11.js' {
  declare module.exports: $Exports<'react-titles/src/Title11'>
}
declare module 'react-titles/src/Title2.js' {
  declare module.exports: $Exports<'react-titles/src/Title2'>
}
declare module 'react-titles/src/Title3.js' {
  declare module.exports: $Exports<'react-titles/src/Title3'>
}
declare module 'react-titles/src/Title4.js' {
  declare module.exports: $Exports<'react-titles/src/Title4'>
}
declare module 'react-titles/src/Title5.js' {
  declare module.exports: $Exports<'react-titles/src/Title5'>
}
declare module 'react-titles/src/Title6.js' {
  declare module.exports: $Exports<'react-titles/src/Title6'>
}
declare module 'react-titles/src/Title7.js' {
  declare module.exports: $Exports<'react-titles/src/Title7'>
}
declare module 'react-titles/src/Title8.js' {
  declare module.exports: $Exports<'react-titles/src/Title8'>
}
declare module 'react-titles/src/Title9.js' {
  declare module.exports: $Exports<'react-titles/src/Title9'>
}
declare module 'react-titles/Title1.js' {
  declare module.exports: $Exports<'react-titles/Title1'>
}
declare module 'react-titles/Title10.js' {
  declare module.exports: $Exports<'react-titles/Title10'>
}
declare module 'react-titles/Title11.js' {
  declare module.exports: $Exports<'react-titles/Title11'>
}
declare module 'react-titles/Title2.js' {
  declare module.exports: $Exports<'react-titles/Title2'>
}
declare module 'react-titles/Title3.js' {
  declare module.exports: $Exports<'react-titles/Title3'>
}
declare module 'react-titles/Title4.js' {
  declare module.exports: $Exports<'react-titles/Title4'>
}
declare module 'react-titles/Title5.js' {
  declare module.exports: $Exports<'react-titles/Title5'>
}
declare module 'react-titles/Title6.js' {
  declare module.exports: $Exports<'react-titles/Title6'>
}
declare module 'react-titles/Title7.js' {
  declare module.exports: $Exports<'react-titles/Title7'>
}
declare module 'react-titles/Title8.js' {
  declare module.exports: $Exports<'react-titles/Title8'>
}
declare module 'react-titles/Title9.js' {
  declare module.exports: $Exports<'react-titles/Title9'>
}
