// flow-typed signature: c694c3e520db0410a198b9c98b3b0337
// flow-typed version: <<STUB>>/react-spinners-kit_v^1.9.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners-kit' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners-kit/lib' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-spinners-kit/lib/index' {
  declare module.exports: $Exports<'react-spinners-kit/lib'>
}
declare module 'react-spinners-kit/lib/index.js' {
  declare module.exports: $Exports<'react-spinners-kit/lib'>
}
